version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
